version: 1.7.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2015
before_build:
 -cmd: pushd . && nuget restore && popd
build:
   project: BreadPlayer.sln
   parallel: true
   verbosity: minimal
deploy: off

