version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2017
configuration:
- FastBuild_Release
platform: x86
before_build:
- cmd: nuget restore BreadPlayer.NoTests.sln
build:
  project: BreadPlayer.NoTests.sln
  parallel: true
  verbosity: minimal
environment:
  UseTemporarySignCert: True
after_build:
- cmd: 7z a BreadPlayer.zip %APPVEYOR_BUILD_FOLDER%\BreadPlayer.Views.UWP\AppPackages\BreadPlayer.Views.UWP_2.7.0.0_FastBuild_Release_Test\*
artifacts:
- path: BreadPlayer.zip
  name: BreadPlayer App Package
  type: Auto

- path: '**\*.appx'
  name: BreadPlayer APPX Package
  type: Auto

- path: '**\*.cer'
  name: BreadPlayer Certificate
  type: Auto

- path: '**\*.appxbundle'
  name: BreadPlayer AppXBundle
  type: Auto
  
