version: 1.8.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2017
configuration: Release
platform: x86
before_build:
- cmd: nuget restore BreadPlayer.NoTests.sln
build:
  project: BreadPlayer.NoTests.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: '**/*.appxbundle'
  name: AppxBundle for BreadPlayer
  type: Auto
notifications:
  - provider: Zapier
    url: https://hooks.zapier.com/hooks/catch/805495/m03qym/    
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
