version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2017
configuration: Release
platform: x86
before_build:
- cmd: >-    
    appveyor DownloadFile https://raw.githubusercontent.com/theweavrs/BreadPlayer/master/ci/Apply.cmd
    appveyor DownloadFile https://raw.githubusercontent.com/theweavrs/BreadPlayer/master/ci/Microsoft.AppxPackage.Targets
    Apply.cmd
    nuget restore BreadPlayer.NoTests.sln
build:
  project: BreadPlayer.NoTests.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: '**/*.appxbundle'
  name: AppxBundle for BreadPlayer
  type: Auto
