version: 1.7.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2015
build_script:
- cmd: >-
    nuget restore BreadPlayer.sln
    set DEVENV="%VS140COMNTOOLS%\..\IDE\devenv"
    %DEVENV% /build "Release|ARM" BreadPlayer.sln
    %DEVENV% /build "Release|x64" BreadPlayer.sln
    %DEVENV% /build "Release|x86" BreadPlayer.sln

