version: 1.8.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2015
configuration: Release
platform: x86
before_build:
- cmd: nuget restore BreadPlayer.sln
build:
  project: BreadPlayer.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: '**/*.appxbundle'
  name: AppxBundle for BreadPlayer
  type: Auto
